# Generated by Django 2.1.5 on 2019-02-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20190222_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', '-exam_grade']},
        ),
    ]
